version: '3.3'

services:
  sample:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app/sample:cached
      - node_modules:/app/sample/node_modules

volumes:
  node_modules: